services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    LuceneSearchBundle\Controller\Admin\SettingsController:
        tags:
            - { name: controller.service_arguments }

    LuceneSearchBundle\Controller\FrontendController: ~

    LuceneSearchBundle\Controller\AutoCompleteController:
        parent: LuceneSearchBundle\Controller\FrontendController

    LuceneSearchBundle\Controller\ListController:
        parent: LuceneSearchBundle\Controller\FrontendController
        calls:
            - [setHighlighterHelper, ['@LuceneSearchBundle\Helper\HighlighterHelper']]
